apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-resources.yaml

images:
  - name: ghcr.io/your-org/vibeyeeter-api
    newTag: REPLACE_WITH_RELEASE_SHA
  - name: ghcr.io/your-org/vibeyeeter-web
    newTag: REPLACE_WITH_RELEASE_SHA
  - name: ghcr.io/your-org/vibeyeeter-tf-runner
    newTag: REPLACE_WITH_RELEASE_SHA

replicas:
  - name: api
    count: 3
  - name: web
    count: 3
