apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    app.kubernetes.io/managed-by: vibeyeeter
    app.kubernetes.io/instance: {{ .Values.appId | quote }}
spec:
  type: ClusterIP
  selector:
    app: app
    app.kubernetes.io/instance: {{ .Values.appId | quote }}
  ports:
    - port: 3000
      targetPort: 3000
